version: '3'
services:
  snippet:
    # what we are building from -> our local ap directory
    build:
      context: ./snippet/
      # dockerfile: /Dockerfile
    ports:
      - '5566:5566'
    # mount our build path ^ into -> the following path:
    volumes:
      - .:/home/app/snippet
      # use a separate volume for node modules because using a BIND causes problems.
      # see "the node_modules trick " here :http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /home/app/snippet/node_modules
  elm-client:
    build:
      context: ./client/
    ports:
      - '8877:8877'
    volumes:
      - .:/home/app/client
      - /home/app/client/node_modules
      - /home/app/client/elm_stuff
